version: '3.1'

services:

  db:
    image: ambiverse/nlu-db-cassandra
    restart: always
    ports:
      - 7000:7000 
      - 7001:7001 
      - 9042:9042 
      - 7199:7199
      - 9160:9160
    environment:
      DATABASE_NAME: aida_20180120_cs_de_en_es_ru_zh_v18

  nlu:
    image: localhost:50000/ambiverse-nlu-local:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      AIDA_CONF: aida_20180120_cs_de_en_es_ru_zh_v18_cass
